// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><meta name=\"color-scheme\" content=\"light dark\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/layout.templ`, Line: 10, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " — Tidal Weather Clock</title><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css\"><script src=\"https://unpkg.com/htmx.org@2/dist/htmx.min.js\"></script><script>\n\t\t\t\tfunction bfFromKts(kts) {\n\t\t\t\t\tconst ms = kts * 0.514444;\n\t\t\t\t\tif (ms < 0.3) return 0; if (ms < 1.6) return 1; if (ms < 3.4) return 2;\n\t\t\t\t\tif (ms < 5.5) return 3; if (ms < 8.0) return 4; if (ms < 10.8) return 5;\n\t\t\t\t\tif (ms < 13.9) return 6; if (ms < 17.2) return 7; if (ms < 20.8) return 8;\n\t\t\t\t\tif (ms < 24.5) return 9; if (ms < 28.5) return 10; if (ms < 32.7) return 11;\n\t\t\t\t\treturn 12;\n\t\t\t\t}\n\t\t\t\tfunction updateBf(el) {\n\t\t\t\t\tconst hint = document.getElementById(el.dataset.bfHint);\n\t\t\t\t\tif (hint) hint.textContent = 'F' + bfFromKts(parseFloat(el.value) || 0);\n\t\t\t\t}\n\t\t\t\tfunction initBfHints(root) {\n\t\t\t\t\t(root || document).querySelectorAll('[data-bf-hint]').forEach(updateBf);\n\t\t\t\t}\n\t\t\t\tdocument.addEventListener('DOMContentLoaded', () => initBfHints());\n\t\t\t\tdocument.addEventListener('htmx:afterSwap', e => initBfHints(e.detail.elt));\n\t\t\t</script></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
