// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activities.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (user_id, name, duration_hrs, window_start, window_end, constraints)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, duration_hrs, window_start, window_end, constraints, created_at, updated_at
`

type CreateActivityParams struct {
	UserID      uuid.UUID       `json:"user_id"`
	Name        string          `json:"name"`
	DurationHrs int32           `json:"duration_hrs"`
	WindowStart int32           `json:"window_start"`
	WindowEnd   int32           `json:"window_end"`
	Constraints json.RawMessage `json:"constraints"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, createActivity,
		arg.UserID,
		arg.Name,
		arg.DurationHrs,
		arg.WindowStart,
		arg.WindowEnd,
		arg.Constraints,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DurationHrs,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Constraints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteActivity = `-- name: DeleteActivity :exec
DELETE FROM activities WHERE id = $1 AND user_id = $2
`

type DeleteActivityParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteActivity(ctx context.Context, arg DeleteActivityParams) error {
	_, err := q.db.ExecContext(ctx, deleteActivity, arg.ID, arg.UserID)
	return err
}

const getActivity = `-- name: GetActivity :one
SELECT id, user_id, name, duration_hrs, window_start, window_end, constraints, created_at, updated_at FROM activities WHERE id = $1 AND user_id = $2
`

type GetActivityParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetActivity(ctx context.Context, arg GetActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, getActivity, arg.ID, arg.UserID)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DurationHrs,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Constraints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivities = `-- name: ListActivities :many
SELECT id, user_id, name, duration_hrs, window_start, window_end, constraints, created_at, updated_at FROM activities WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListActivities(ctx context.Context, userID uuid.UUID) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listActivities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.DurationHrs,
			&i.WindowStart,
			&i.WindowEnd,
			&i.Constraints,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActivity = `-- name: UpdateActivity :one
UPDATE activities
SET name = $3,
    duration_hrs = $4,
    window_start = $5,
    window_end   = $6,
    constraints  = $7,
    updated_at   = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, duration_hrs, window_start, window_end, constraints, created_at, updated_at
`

type UpdateActivityParams struct {
	ID          uuid.UUID       `json:"id"`
	UserID      uuid.UUID       `json:"user_id"`
	Name        string          `json:"name"`
	DurationHrs int32           `json:"duration_hrs"`
	WindowStart int32           `json:"window_start"`
	WindowEnd   int32           `json:"window_end"`
	Constraints json.RawMessage `json:"constraints"`
}

func (q *Queries) UpdateActivity(ctx context.Context, arg UpdateActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, updateActivity,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.DurationHrs,
		arg.WindowStart,
		arg.WindowEnd,
		arg.Constraints,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DurationHrs,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Constraints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
