// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMagicLink = `-- name: CreateMagicLink :one
INSERT INTO magic_links (token, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token, user_id, expires_at, used_at
`

type CreateMagicLinkParams struct {
	Token     string    `json:"token"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) (MagicLink, error) {
	row := q.db.QueryRowContext(ctx, createMagicLink, arg.Token, arg.UserID, arg.ExpiresAt)
	var i MagicLink
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token, user_id, expires_at, created_at
`

type CreateSessionParams struct {
	Token     string    `json:"token"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const getMagicLink = `-- name: GetMagicLink :one
SELECT token, user_id, expires_at, used_at FROM magic_links
WHERE token = $1
  AND used_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetMagicLink(ctx context.Context, token string) (MagicLink, error) {
	row := q.db.QueryRowContext(ctx, getMagicLink, token)
	var i MagicLink
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getOrCreateUser = `-- name: GetOrCreateUser :one
INSERT INTO users (email)
VALUES ($1)
ON CONFLICT (email) DO UPDATE SET email = EXCLUDED.email
RETURNING id, email, created_at
`

func (q *Queries) GetOrCreateUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateUser, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT
    s.token        AS session_token,
    s.expires_at   AS session_expires_at,
    s.created_at   AS session_created_at,
    u.id           AS user_id,
    u.email        AS user_email,
    u.created_at   AS user_created_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token = $1
  AND s.expires_at > now()
`

type GetSessionWithUserRow struct {
	SessionToken     string    `json:"session_token"`
	SessionExpiresAt time.Time `json:"session_expires_at"`
	SessionCreatedAt time.Time `json:"session_created_at"`
	UserID           uuid.UUID `json:"user_id"`
	UserEmail        string    `json:"user_email"`
	UserCreatedAt    time.Time `json:"user_created_at"`
}

func (q *Queries) GetSessionWithUser(ctx context.Context, token string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionWithUser, token)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.SessionToken,
		&i.SessionExpiresAt,
		&i.SessionCreatedAt,
		&i.UserID,
		&i.UserEmail,
		&i.UserCreatedAt,
	)
	return i, err
}

const markMagicLinkUsed = `-- name: MarkMagicLinkUsed :exec
UPDATE magic_links
SET used_at = now()
WHERE token = $1
`

func (q *Queries) MarkMagicLinkUsed(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, markMagicLinkUsed, token)
	return err
}
