// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hourly_data.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getHourlyDataForLocation = `-- name: GetHourlyDataForLocation :many
SELECT id, location_id, time, wind_speed_ms, wind_dir_deg, weather_code, tide_height_m, fetched_at, temperature_celsius FROM hourly_data
WHERE location_id = $1
  AND time >= $2
  AND time < $3
ORDER BY time
`

type GetHourlyDataForLocationParams struct {
	LocationID uuid.UUID `json:"location_id"`
	Time       time.Time `json:"time"`
	Time_2     time.Time `json:"time_2"`
}

func (q *Queries) GetHourlyDataForLocation(ctx context.Context, arg GetHourlyDataForLocationParams) ([]HourlyDatum, error) {
	rows, err := q.db.QueryContext(ctx, getHourlyDataForLocation, arg.LocationID, arg.Time, arg.Time_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HourlyDatum
	for rows.Next() {
		var i HourlyDatum
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Time,
			&i.WindSpeedMs,
			&i.WindDirDeg,
			&i.WeatherCode,
			&i.TideHeightM,
			&i.FetchedAt,
			&i.TemperatureCelsius,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTideHeight = `-- name: UpsertTideHeight :exec
INSERT INTO hourly_data (location_id, time, wind_speed_ms, wind_dir_deg, weather_code, tide_height_m)
VALUES ($1, $2, 0, 0, '', $3)
ON CONFLICT (location_id, time) DO NOTHING
`

type UpsertTideHeightParams struct {
	LocationID  uuid.UUID `json:"location_id"`
	Time        time.Time `json:"time"`
	TideHeightM float64   `json:"tide_height_m"`
}

func (q *Queries) UpsertTideHeight(ctx context.Context, arg UpsertTideHeightParams) error {
	_, err := q.db.ExecContext(ctx, upsertTideHeight, arg.LocationID, arg.Time, arg.TideHeightM)
	return err
}

const upsertWeatherData = `-- name: UpsertWeatherData :exec
INSERT INTO hourly_data (location_id, time, wind_speed_ms, wind_dir_deg, weather_code, tide_height_m, temperature_celsius)
VALUES ($1, $2, $3, $4, $5, 0, $6)
ON CONFLICT (location_id, time) DO UPDATE SET
    wind_speed_ms       = EXCLUDED.wind_speed_ms,
    wind_dir_deg        = EXCLUDED.wind_dir_deg,
    weather_code        = EXCLUDED.weather_code,
    temperature_celsius = EXCLUDED.temperature_celsius,
    fetched_at          = now()
`

type UpsertWeatherDataParams struct {
	LocationID         uuid.UUID `json:"location_id"`
	Time               time.Time `json:"time"`
	WindSpeedMs        float64   `json:"wind_speed_ms"`
	WindDirDeg         float64   `json:"wind_dir_deg"`
	WeatherCode        string    `json:"weather_code"`
	TemperatureCelsius float64   `json:"temperature_celsius"`
}

func (q *Queries) UpsertWeatherData(ctx context.Context, arg UpsertWeatherDataParams) error {
	_, err := q.db.ExecContext(ctx, upsertWeatherData,
		arg.LocationID,
		arg.Time,
		arg.WindSpeedMs,
		arg.WindDirDeg,
		arg.WeatherCode,
		arg.TemperatureCelsius,
	)
	return err
}
