// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const ensureLocation = `-- name: EnsureLocation :exec
INSERT INTO locations (user_id, name, lat, lon)
VALUES ($1, 'Burnham Overy Staithe', 52.963583, 0.74417)
ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) EnsureLocation(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, ensureLocation, userID)
	return err
}

const getLocationByUser = `-- name: GetLocationByUser :one
SELECT id, user_id, name, lat, lon, created_at FROM locations WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetLocationByUser(ctx context.Context, userID uuid.UUID) (Location, error) {
	row := q.db.QueryRowContext(ctx, getLocationByUser, userID)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Lat,
		&i.Lon,
		&i.CreatedAt,
	)
	return i, err
}
