// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Activity struct {
	ID          uuid.UUID       `json:"id"`
	UserID      uuid.UUID       `json:"user_id"`
	Name        string          `json:"name"`
	DurationHrs int32           `json:"duration_hrs"`
	WindowStart int32           `json:"window_start"`
	WindowEnd   int32           `json:"window_end"`
	Constraints json.RawMessage `json:"constraints"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type HourlyDatum struct {
	ID          uuid.UUID `json:"id"`
	LocationID  uuid.UUID `json:"location_id"`
	Time        time.Time `json:"time"`
	WindSpeedMs float64   `json:"wind_speed_ms"`
	WindDirDeg  float64   `json:"wind_dir_deg"`
	WeatherCode string    `json:"weather_code"`
	TideHeightM float64   `json:"tide_height_m"`
	FetchedAt   time.Time `json:"fetched_at"`
}

type Location struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Lat           float64   `json:"lat"`
	Lon           float64   `json:"lon"`
	CreatedAt     time.Time `json:"created_at"`
	TideStationID string    `json:"tide_station_id"`
}

type MagicLink struct {
	Token     string     `json:"token"`
	UserID    uuid.UUID  `json:"user_id"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
}

type Session struct {
	Token     string    `json:"token"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

type UserLocation struct {
	UserID     uuid.UUID `json:"user_id"`
	LocationID uuid.UUID `json:"location_id"`
}
